name: Linting Check

on:
  push: 
  pull_request:
    branches:
      - main


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.0

      - name: Install Dependencies
        run: flutter pub get
      
      - name: Run Flutter Analyze
        run: flutter analyze
      

